### PR TITLE
#73 Add Kicktime to kick_$.tfs

### PR DESCRIPTION
**Pull request by JoschD**
* Refactored kick.py to use only constants as Column names
  * harpy/handler.py: added TIME to headers.
  * accelerator.py: refactored strings of element types to AccElementTypes class

### CODE REVIEW

**Comment by mihofer** [comment]
https://github.com/pylhc/omc3/blob/4ad993aaec370c9fab2e1b14d396a31c27d5a8a0/omc3/harpy/handler.py#L145-L158

why not use instead of just date as argument a dict containing additional headers, would allow to easily implement more headers at a later point if needed

**Comment by mihofer** [comment]
https://github.com/pylhc/omc3/blob/4ad993aaec370c9fab2e1b14d396a31c27d5a8a0/omc3/optics_measurements/kick.py#L47-L50

maybe change to RESCALE_FACTOR{plane}, kick files could then be merged without name clash

**Comment by mihofer** [comment]
should optic_measurements/constants.py be put in definitions as other scripts (kmod, amp. det script, ..) should also rely on the conventions established there?

**Comment by JoschD** [comment]
> https://github.com/pylhc/omc3/blob/4ad993aaec370c9fab2e1b14d396a31c27d5a8a0/omc3/harpy/handler.py#L145-L158
> 
> why not use instead of just date as argument a dict containing additional headers, would allow to easily implement more headers at a later point if needed

A dict would make sense if the headers are added automatically. But as there is some formatting going on, one has to handle each entry individually anyway (most likely). Changing `date` to `addition_headers` later if needed should be no problem though.

**Comment by JoschD** [comment]
> should optic_measurements/constants.py be put in definitions as other scripts (kmod, amp. det script, ..) should also rely on the conventions established there?

Yes... but we need come to some convetion later. New issue, I guess

**Comment by JoschD** [comment]
> https://github.com/pylhc/omc3/blob/4ad993aaec370c9fab2e1b14d396a31c27d5a8a0/omc3/optics_measurements/kick.py#L47-L50
> 
> maybe change to RESCALE_FACTOR{plane}, kick files could then be merged without name clash

Maybe. Also new issue to talk about.

**Pull request merged**
