### PR TITLE
Feature/GitHub actions

### LINKED ISSUE #224: Implement full matrix test builds (Travis / Github Actions)
It is time to test our package(s) on all supported python versions across major operating systems.

From personal experience:

- Travis builds are extremely slow under a big matrix as only 2 or 3 will run concurrently
- Travis' `macOS` VMs take a very long time to spin up (~10-15 min)
- Travis support for `Windows` is still experimental.
- Github Actions don't have these problems
- Github Actions "only" offers `macos-latest` and `windows-latest` for these systems.

I started setting up github actions in the `feature/github_actions` branch.
This was branched off from `bugs/219/madx_macros` as it should soon be merged into `master`, but did reset the `tfs-pandas` dependency to `>=1.0` in order for the install step to not fail

We're expecting to find bugs in the new builds, will gather findings in this issue.

Commits that were pushed previously without referencing this issue: 92bed47, 73a3cf3, 6474dba and 10cf7b0

### PR DESCRIPTION
**Pull request by mihofer**
add testing via github actions
Fixes #224

### CODE REVIEW

**Comment by fsoubelet** [comment]
Just to be clear I am not done with this yet

**Comment by fsoubelet** [comment]
Note to self: basic tests are being ran by GA on PRs, which is wrong and needs to be fixed. Will do tonight

**Comment by fsoubelet** [comment]
Expecting windows builds to pass once PR [32](https://github.com/pylhc/generic_parser/pull/32) from `generic_parser` is done, and its `1.0.7` release makes it into `omc3`'s CI pipeline.

The error is currently windows complaining about the strings when reading from the ini files `generic_parser` creates when saving config options.

Additionnally, the fix for #239 is implemented in this PR, which will allow closing #240 once we merge.

**Comment by fsoubelet** [comment]
Also, I saw that `Python 3.9` just got realised today. Depending on how quickly this PR moves, I might add a commit to include `3.9` in the builds.


Will also depends on how quickly `3.9` is available for GA, which should be very quick.

**Comment by lmalina** [comment]
> Also, I saw that `Python 3.9` just got realised today. Depending on how quickly this PR moves, I might add a commit to include `3.9` in the builds.
> 
> Will also depends on how quickly `3.9` is available for GA, which should be very quick.

Question is also how quickly will our dependencies support `3.9`...

**Comment by fsoubelet** [comment]
Builds now pass also on windows thanks to `generic_parser 1.0.7`. This should be ready for review. I committed linting changes out of habit so it will be an annoying review, sorry.

Main takeways:
- implementing github actions
- creating a README to detail the workflows
- removing travis CI
- moving the changelog to its own file
- cleanup of unused commands in the makefile
- small updates to main README, mainly the build badge
- adding an outputdir option for `analyse_kmod` (#239) that defaults to the `working_directory`
- removing messy fixtures in tests in favor of `pytest`'s own `tmp_path`
- some linting / pep8-ifying (blackt / pycharm's `optimize imports`)

Remaining:
- Modifying the PR requirements (stop requiring travis CI status, require the extended tests from GA) @JoschD

**Review by JoschD — DISMISSED** [review]
Wait for @lmalina's approval

**Comment by fsoubelet** [comment]
Should be an easier review now

**Review by lmalina — APPROVED** [review]
Nice work, not hidden anymore in the flood of linting 👍  (few files could still be removed from from this PR, but let's stay pragmatic)

**Pull request merged**
